name: FTPS Test

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: 🚀 Deploy website every commit
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2

      - name: 📂 Sync files
        uses: hazemwehbi/csv-data-reader@master
        with:
          server: ${{ secrets.SERVER}}
          username: ${{ secrets.USERNAME}}
          password: ${{ secrets.PASSWORD}}
